version: '3.8'

services:
  api-astrologica:
    build: .
    image: api-astrologica:latest
    container_name: api-astrologica
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-astrologica-dev.rule=Host(`api.astrologia.illumiai.com`)"
      - "traefik.http.routers.api-astrologica-dev.entrypoints=websecure"
      - "traefik.http.routers.api-astrologica-dev.tls=true"
      - "traefik.http.services.api-astrologica-dev.loadbalancer.server.port=8000"
      - "traefik.docker.network=network_public"
    networks:
      - network_public

networks:
  network_public:
    external: true 